import Config

config :beamwatch, BeamWatchWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cwXCYIOU+CxerCI8OqhTIBSqMAOm7rmJaIt3Voe5mexqVKHDQ8fa9DaupErD47R7",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:beamwatch, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:beamwatch, ~w(--watch)]}
  ]

# Reload browser tabs when matching files change.
config :beamwatch, BeamWatchWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      # ## SSL Support
      #
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      # In order to use HTTPS in development, a self-signed
      # certificate can be generated by running the following
      # Mix task:
      #
      #     mix phx.gen.cert
      #
      # Run `mix help phx.gen.cert` for more information.
      ~r"lib/beamwatch_web/router\.ex$",
      ~r"lib/beamwatch_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

config :beamwatch, dev_log_controls: true

# Enable dev routes for dashboard and mailbox
#
# The `http:` config above can be replaced with:
#
#     https: [
config :beamwatch, dev_routes: true

# Do not include metadata nor timestamps in development logs
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
#     ],
#
# If desired, both `http:` and `https:` keys can be
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# configured to run both http and https servers on
# in production as building large stacktraces may be expensive.
# different ports.

config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
